### ISSUE TITLE
[Location] See 'Old Toronto' after changing the location to 'Toronto'

### ISSUE THREAD

**Issue by avakris** [nightfallb612/BeWear-Test#11]
**Describe the bug**

**To Reproduce**
1. Go to 'Homepage'
2. Click on 'Location search' > 'Toronto'
3. Click on 'search'
4. See 'Old Toronto'

**Expected behavior**
We should see only Toronto.

**Screenshots**
https://drive.google.com/file/d/1Xr1cxcHNTDoMd1tXgqEFTpWoVTtsYeCj/view?usp=sharing

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: chrome
 - Version: 106.0.5249.119 

Thank you.

**Comment by nightfallb612** [comment]
We using openweather api for searching city.
When user input "Toronto", api returns its name "Old Toronto". 
This is the openweather api problem. So, It is hard to fixed our web.
So, please leave it current status.
