### ISSUE TITLE
[Common] Displayed white dot beside logo.

### ISSUE THREAD

**Issue by nightfallb612** [nightfallb612/BeWear-Test#12]
**Describe the bug**
Displayed white dot beside logo.

**To Reproduce**
1. Login with Google
2. Displayed white dot beside logo.

**Expected behavior**
Didn't display white dot beside logo.

**Screenshots**
![image](https://user-images.githubusercontent.com/50945896/201535937-ba080714-29fb-42b0-ad50-05eb230cc200.png)

**Desktop (please complete the following information):**
 - OS: Window
 - Browser Chorme

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ghost** [comment]
[Cause]
Test hamburger menu button was appearing as the white dot.

[Fix]
Remove the testing code
 
**fixed code** -  https://github.com/nightfallb612/BeWear-eats-Teambits/pull/80#issue-1447147315
