### ISSUE TITLE
[Today/Tomorrow] Hourly temperature information range when "Next" clicked

### ISSUE THREAD

**Issue by flachonso** [nightfallb612/BeWear-Test#19]
**Describe the bug**
Webapp just shows one next "hourly temperature" in Today and Tomorrow's page

**To Reproduce**
1. Go to Today or Tomorrow page
2. Click on "Next" in "Hourly Temperature" Section, on the footer
4. See just one piece of information getting pulled (the next hour)

**Expected behavior**
Fill at least half of the screen with new information when "Next" is clicked on the "Hourly Temperature" section on the Today and Tomorrow's page.

**Comment by ghost** [comment]
Fixed at [https://github.com/nightfallb612/BeWear-eats-Teambits/pull/86](url)
