### ISSUE TITLE
[Common] Unit doesn't change after users change unit setting in setting page

### ISSUE THREAD

**Issue by ghost** [nightfallb612/BeWear-Test#21]
**Describe the bug**
When user change temperature setting, it doesn't apply that.

**To Reproduce**
1. Go to Setting
2. Change unit settings and save
3. Go to today/tomorrow/7days

**Expected behavior**
The unit should reflect what the user has set

**Screenshots**
<img width="652" alt="Screen Shot 2022-11-17 at 13 59 44" src="https://user-images.githubusercontent.com/25358256/202569072-191535ca-fea3-4b4e-b045-615c775d5637.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nightfallb612** [comment]
[Cause]
 - Didn't change localstorage when finish setting

[Fixed]
 - Changed localstorage when finish setting
 - Display alert message when finished setting
   ( https://github.com/nightfallb612/BeWear-eats-Teambits/pull/99 )
