### ISSUE TITLE
[Setting] Items are not aligned

### ISSUE THREAD

**Issue by ghost** [nightfallb612/BeWear-Test#23]
**Describe the bug**
Items in setting screen are not aligned with logo

**To Reproduce**
1. Go to setting page
2. See error

**Expected behavior**
Items are supposed to be aligned with logo

**Screens
<img width="379" alt="Screen Shot 2022-11-17 at 14 21 11" src="https://user-images.githubusercontent.com/25358256/202572646-d73bdf42-2e74-44c0-9184-0cd7200d7067.png">
<img width="347" alt="Screen Shot 2022-11-17 at 14 21 45" src="https://user-images.githubusercontent.com/25358256/202572648-5438b7d3-6aad-4a31-8f49-352000ff5d06.png">
hots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dkiatsongsak00** [comment]
Done!
