### ISSUE TITLE
[Outfit] Loading image didn't show sometimes.

### ISSUE THREAD

**Issue by nightfallb612** [nightfallb612/BeWear-Test#24]
**Describe the bug**
Loading image didn't show sometimes

**To Reproduce**
1. Loged in with any account.
2. Loading image didn't show today page.

**Expected behavior**
Loading image must to show while outfit was loading.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ghost** [comment]
Fixed at [https://github.com/nightfallb612/BeWear-eats-Teambits/pull/97](url)
