### ISSUE TITLE
Anonymous able to access other pages

### ISSUE THREAD

**Issue by dkiatsongsak00** [nightfallb612/BeWear-Test#27]
**Describe the bug**
Anonymous able to access Tomorrow, 7 days and Settings page

**To Reproduce**
1. Go to 'Login'
2. Click on 'Skip'
3. Click on Navigation bar

**Expected behavior**
Once Anonmous user click on Tomorrow, 7 days, Settings -> Redirect to Login/Signup page

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome

**Smartphone (please complete the following information):**
 - Device: iPhone11
 - OS: iOS8.1
 - Browser: Chrome

**Comment by nightfallb612** [comment]
[Cause]
 - There was no menu access restriction.

[Fixed]
 - "Anonymous" user only display "Today" Menu.
   ( https://github.com/nightfallb612/BeWear-eats-Teambits/pull/108 )

**Comment by ghost** [comment]
Fixed
