### ISSUE TITLE
Layout changes on screen refresh.

### ISSUE THREAD

**Issue by nightfallb612** [nightfallb612/BeWear-Test#28]
**Describe the bug**
Layout changes on screen refresh.

**To Reproduce**
1. Login with Google.
2. Screen refresh any menu.
3. Layout changes on screen refresh.

**Expected behavior**
Keep Layout while screen refresh.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Window
 - Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nightfallb612** [comment]
[Cause]
 - I am caching css for offline mode. This caused the cached css to be used even when creating new css.

[Fixed]
 - Expel css from caching item for display offline mode.
   ( https://github.com/nightfallb612/BeWear-eats-Teambits/pull/107 )

**Comment by ghost** [comment]
Fixed at https://github.com/nightfallb612/BeWear-eats-Teambits/pull/107
