### ISSUE TITLE
Morning, Afternoon, Evening Icon not showing

### ISSUE THREAD

**Issue by dkiatsongsak00** [nightfallb612/BeWear-Test#30]
**Describe the bug**
Morning, Afternoon, Evening Icon not showing in Today/Tomorrow/7 days forecast page

**To Reproduce**
1. Go to 'Today', 'Tomorrow', '7 days forecast'
2. Click on 'Morning', 'Afternoon', 'Evening'
3. See error

**Expected behavior**
Icon showing for Morning, Afternoon, Evening

**Screenshots**
<img width="414" alt="Screen Shot 2565-11-21 at 20 51 48" src="https://user-images.githubusercontent.com/114777509/203225202-299a52b0-ca72-406e-b101-95c834c7299c.png">

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome

**Smartphone (please complete the following information):**
 - Device: iPhone11
 - OS: iOS
 - Browser: Chrome

**Comment by ghost** [comment]
Fixed and merged!
